language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install numpy jaxlib jax tensorflow tensorflow-datasets --upgrade
  - pip install -e .
script:
  - set -e
  - for f in tests/*.py; do python $f; done
